name: Build release & deploy

on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/cache@v2
        with:
          path: ./node_modules
          key: modules-${{ hashFiles('package-lock.json') }}
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install
      - run: npx webpack bundle --no-watch --mode production
      - uses: trmcnvn/firefox-addon@v1
        name: Firefox upload
        with:
          # uuid is only necessary when updating an existing addon,
          # omitting it will create a new addon
          uuid: 'la-remote-actions@qualityunit.com'
          xpi: output/liveagent_web_contact_cards-firefox.zip
          manifest: manifest.json
          api-key: ${{ secrets.FIREFOX_API_KEY }}
          api-secret: ${{ secrets.FIREFOX_API_SECRET }}
#      - uses: trmcnvn/chrome-addon@v2
#        name: Chrome upload
#        with:
#          # extension is only necessary when updating an existing addon,
#          # omitting it will create a new addon
#          extension: aolfiecgellhcfcblocebkbdmnmjnngd
#          zip: output/liveagent_web_contact_cards-chromium.zip
#          client-id: ${{ secrets.CHROME_CLIENT_ID }}
#          client-secret: ${{ secrets.CHROME_CLIENT_SECRET }}
#          refresh-token: ${{ secrets.CHROME_REFRESH_TOKEN }}
      - name: Chrome upload
        uses: mnao305/chrome-extension-upload@1.1.1
        with:
          file-path: output/liveagent_web_contact_cards-firefox.zip
          extension-id: aolfiecgellhcfcblocebkbdmnmjnngd
          client-id: ${{ secrets.CHROME_CLIENT_ID }}
          client-secret: ${{ secrets.CHROME_CLIENT_SECRET }}
          refresh-token: ${{ secrets.CHROME_REFRESH_TOKEN }}