name: Build release & deploy

on:
  push:
    tags:
      - 'v*.*.*'
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/cache@v2
        with:
          path: ./node_modules
          key: modules-${{ hashFiles('package-lock.json') }}
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
      - run: npm install
      - run: npx webpack bundle --no-watch --mode production
      - uses: trmcnvn/firefox-addon@v1
        with:
          # uuid is only necessary when updating an existing addon,
          # omitting it will create a new addon
           uuid: '{la-remote-actions@qualityunit.com}'
          xpi: output/liveagent_web_contact_cards.zip
          manifest: manifest.json
          api-key: ${{ secrets.FIREFOX_API_KEY }}
          api-secret: ${{ secrets.FIREFOX_API_SECRET }}
